/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Poppins', 'sans-serif'],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["32px", {"lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "h3": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "button": ["15px", {"lineHeight": "1", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "#0077B6",
        success: "#6A994E",
        danger: "var(--danger)",
        warning: "#E9C46A",
        card: "var(--card)",
        border: "var(--border)",
        text: "var(--text)",
        info: "#0EA5E9",
        black: "#0F172A",
        white: "#FFFFFF",
        surface: "#EDEDE9",
        "on-background": "#003049",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#ebeef4",
        "on-primary": "#ffffff",
        "primary-container": "#0077B6",
        "on-surface-variant": "#404850",
        "surface-container-highest": "#e0e2e8",
        "surface-container-high": "#e6e8ee",
        "surface-container-low": "#f1f4f9",
        "surface-variant": "#e0e2e8",
        "on-error": "#ffffff",
        secondary: "#45617b",
        tertiary: "#864a00",
        "inverse-surface": "#2d3135",
        "outline-variant": "#bfc7d1",
        "on-surface": "#003049",
        outline: "#707881",
        error: "#ba1a1a",
        dark: "#003049",
        accent: "#DA627D",
        gray: {
          50: "#F8FAFC",
          100: "#F1F5F9",
          200: "#E2E8F0",
          300: "#CBD5F5",
          400: "#94A3B8",
          500: "#64748B",
          600: "#475569",
          700: "#334155",
          800: "#1E293B",
          900: "#020617",
        }
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "container-max": "1440px",
        "sm": "12px",
        "lg": "40px",
        "md": "24px",
        "xs": "4px",
        "xl": "64px"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      backgroundImage: {
        'premium-gradient': 'linear-gradient(135deg, #0F172A, #020617)',
        'btn-gradient': 'linear-gradient(to right, #2563EB, #22C55E)',
      },
      boxShadow: {
        'glow-blue': '0 0 15px rgba(37, 99, 235, 0.6)',
        'glow-green': '0 0 15px rgba(34, 197, 94, 0.6)',
        'glow-red': '0 0 20px rgba(239, 68, 68, 0.6)',
        'glow-gold': '0 0 20px rgba(255, 215, 0, 0.8)',
        'soft': '0 4px 6px -1px rgba(0, 48, 73, 0.05), 0 10px 15px -3px rgba(0, 48, 73, 0.1)',
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
