import React from "react";
import { X, Printer, Download, Eye } from "lucide-react";
import { PrintJob } from "../types/printing.types";
import { generateInvoiceNumber, calculateTotal } from "../utils/print.utils";

interface PrintPreviewModalProps {
  job: PrintJob;
  onClose: () => void;
  onPrint: () => void;
}

export const PrintPreviewModal: React.FC<PrintPreviewModalProps> = ({ job, onClose, onPrint }) => {
  // Mock data for preview layout
  const invoiceNum = generateInvoiceNumber();
  const date = new Date(job.createdAt).toLocaleDateString();
  const items = [
    { id: "1", name: "Premium Mobile Case - X20", price: 25.00, quantity: 2 },
    { id: "2", name: "Fast Charger 3.0", price: 15.00, quantity: 1 }
  ];
  const total = calculateTotal(items);

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm animate-in fade-in duration-300">
      <div className="w-full max-w-2xl bg-white text-gray-900 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Modal Header */}
        <div className="bg-gray-50 p-4 border-b flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Eye className="text-gray-400" size={20} />
            <h2 className="font-bold">Print Preview</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-200 rounded-full transition-colors text-gray-500">
            <X size={20} />
          </button>
        </div>

        {/* Invoice Area */}
        <div className="flex-1 overflow-y-auto p-8 font-mono text-xs">
          <div className="border border-gray-200 p-8 shadow-sm bg-white rounded-lg max-w-md mx-auto">
            <div className="text-center mb-8">
              <h1 className="text-xl font-black uppercase tracking-tighter">TIJARAT PRO ERP</h1>
              <p className="text-[10px] text-gray-500 uppercase">Premium Retail Solution</p>
            </div>

            <div className="flex justify-between mb-8 pb-4 border-b border-dashed">
              <div>
                <p className="text-gray-400 mb-1">INVOICE TO</p>
                <p className="font-bold text-sm uppercase">{job.customerName}</p>
              </div>
              <div className="text-right">
                <p className="font-bold">#{invoiceNum}</p>
                <p className="text-gray-500">{date}</p>
              </div>
            </div>

            <table className="w-full mb-8 text-left">
              <thead>
                <tr className="border-b border-gray-100">
                  <th className="py-2">ITEM</th>
                  <th className="py-2 text-right">QTY</th>
                  <th className="py-2 text-right">PRICE</th>
                  <th className="py-2 text-right">TOTAL</th>
                </tr>
              </thead>
              <tbody>
                {items.map(item => (
                  <tr key={item.id} className="border-b border-gray-50">
                    <td className="py-3 uppercase text-[10px] leading-tight">{item.name}</td>
                    <td className="py-3 text-right">{item.quantity}</td>
                    <td className="py-3 text-right">${item.price.toFixed(2)}</td>
                    <td className="py-3 text-right font-bold">${(item.price * item.quantity).toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <div className="flex justify-between items-center pt-4 border-t-2 border-black">
              <span className="font-black text-lg">TOTAL</span>
              <span className="font-black text-lg">${total.toFixed(2)}</span>
            </div>

            <div className="mt-12 text-center text-[10px] text-gray-400">
              <p>THANK YOU FOR YOUR BUSINESS</p>
              <p className="mt-1">Generated by TijaratPro Printing Gateway</p>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-gray-50 border-t flex items-center justify-between gap-4">
          <button className="flex items-center gap-2 px-4 py-2 text-sm font-bold text-gray-600 hover:bg-gray-200 rounded-lg transition-colors">
            <Download size={18} /> Save PDF
          </button>
          
          <div className="flex items-center gap-2">
            <button 
              onClick={onClose}
              className="px-6 py-2 text-sm font-bold text-gray-400 hover:text-gray-600"
            >
              Cancel
            </button>
            <button 
              onClick={onPrint}
              className="flex items-center gap-2 px-8 py-2 bg-blue-600 text-white rounded-lg font-black hover:bg-blue-700 transition-all shadow-lg active:scale-95"
            >
              <Printer size={18} /> PRINT NOW
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
